const missions = [
  { title:'Find Your Home', desc:'Anchor your fingers on A · T · E · H.', keys:'ATEHDS', rounds:['tdt asa the tdt asa the','asaet tdtha asset tdtha','detah saeth detah saeth'] },
  { title:'Steady Steps', desc:'Turn home-row movements into familiar words.', keys:'ATEHDS', rounds:['detest heated dates','stated sedate heaths','she has heated these'] },
  { title:'Common Ground', desc:'Build rhythm with high-frequency words.', keys:'ATEHDS', rounds:['as she sat he sees','see that he has dated','she ate dates at tea'] },
  { title:'Reach North', desc:'Add R · O · L · N without losing your anchor.', keys:'ATEHDSROLN', rounds:['near the northern shore','learn a short line','the lantern rose'] },
  { title:'Open the Map', desc:'Explore G · F · J · M · P · B · Q.', keys:'ATEHDSROLNGFJMPBQ', rounds:['form a bold plan','jump from the green path','bring a map for her'] },
  { title:'Lower Trail', desc:'Reach down for Z · Y · C · K · W · V.', keys:'ABCDEFGHIJKLMNOPQRSTUVWXYZ', rounds:['walk very quickly','carry your brave work','a cozy view at dawn'] },
  { title:'Word Sprint', desc:'Keep a smooth pace through full sentences.', keys:'ABCDEFGHIJKLMNOPQRSTUVWXYZ', rounds:['steady hands make accurate work','speed grows from a relaxed rhythm','look ahead and trust your fingers'] },
  { title:'Summit Run', desc:'Put the entire letter layout together.', keys:'ABCDEFGHIJKLMNOPQRSTUVWXYZ', rounds:['the quick brown fox jumps over a lazy dog','practice with purpose and patience','accuracy first then let speed follow'] }
];

const rows = [
  [{c:'X',f:'index'},{c:'G',f:'index'},{c:'M',f:'middle'},{c:'P',f:'ring'},{c:'B',f:'little'},{c:'Q',f:'little'}],
  [{c:'J',f:'index'},{c:'F',f:'index'},{c:'D',f:'middle'},{c:'O',f:'ring'},{c:'L',f:'little'},{c:'R',f:'little'}],
  [{c:'S',f:'index'},{c:'A',f:'index'},{c:'T',f:'middle'},{c:'E',f:'ring'},{c:'H',f:'little'},{c:'N',f:'little'}],
  [{c:'Z',f:'index'},{c:'Y',f:'index'},{c:'C',f:'middle'},{c:'K',f:'ring'},{c:'W',f:'little'},{c:'V',f:'little'}]
];
const fingerNames={index:'index finger',middle:'middle finger',ring:'ring finger',little:'little finger',thumb:'thumb'};
const $=s=>document.querySelector(s);
const state={mission:0,round:0,pos:0,typed:0,correct:0,streak:0,bestStreak:0,score:0,xp:0,unlocked:0,completed:[],start:0,timer:null,sound:true,errors:new Set()};

function load(){try{const p=JSON.parse(localStorage.getItem('rhq-progress'));if(p){state.xp=p.xp||0;state.unlocked=Math.min(p.unlocked||0,missions.length-1);state.completed=p.completed||[];state.sound=p.sound!==false}}catch(e){}}
function save(){localStorage.setItem('rhq-progress',JSON.stringify({xp:state.xp,unlocked:state.unlocked,completed:state.completed,sound:state.sound}))}
function buildKeyboard(el){el.innerHTML='';rows.flat().forEach((k,i)=>{const key=document.createElement('div');key.className=`key f-${k.f}${['A','T','E','H'].includes(k.c)?' home':''}`;key.dataset.key=k.c.toLowerCase();key.textContent=k.c;key.style.gridRow=Math.floor(i/6)+1;key.style.gridColumn=(i%6)+1;el.append(key)});const extras=[[' ','SPACE','space home','1/5'],['i','I','thumb-i','1'],['u','U','thumb-u','2'],['Enter','ENTER','thumb-enter','3/5']];extras.forEach(([data,label,cls,row])=>{const key=document.createElement('div');key.className=`key f-thumb ${cls}`;key.dataset.key=data;key.textContent=label;key.style.gridRow=row;key.style.gridColumn=cls.startsWith('space')?7:8;el.append(key)})}
function renderMissions(){const box=$('#missionList');box.innerHTML='';missions.forEach((m,i)=>{const b=document.createElement('button');const locked=i>state.unlocked;b.className=`mission ${i===state.mission?'active':''} ${locked?'locked':''}`;b.disabled=locked;b.innerHTML=`<span class="mission-num">${state.completed.includes(i)?'✓':String(i+1).padStart(2,'0')}</span><span><b>${m.title}</b><small>${locked?'LOCKED':state.completed.includes(i)?'COMPLETE':m.keys.length+' KEYS'}</small></span><span class="check">${i===state.mission?'›':''}</span>`;b.onclick=()=>selectMission(i);box.append(b)});$('#missionCount').textContent=`${state.mission+1} / ${missions.length}`}
function selectMission(i){if(i>state.unlocked)return;clearInterval(state.timer);Object.assign(state,{mission:i,round:0,pos:0,typed:0,correct:0,streak:0,bestStreak:0,score:0,start:0,errors:new Set()});renderMissions();renderMission();focusInput()}
function renderMission(){const m=missions[state.mission];$('#missionLabel').textContent=`MISSION ${String(state.mission+1).padStart(2,'0')}`;$('#missionTitle').textContent=m.title;$('#missionDesc').textContent=m.desc;$('#roundLabel').textContent=`ROUND ${state.round+1} / ${m.rounds.length}`;renderPrompt();updateStats();updateRank()}
function renderPrompt(){const text=currentText(),frag=document.createDocumentFragment();[...text].forEach((ch,i)=>{const s=document.createElement('span');s.textContent=ch===' '?'\u00a0':ch;if(i<state.pos)s.className=state.errors.has(i)?'wrong':'done';else if(i===state.pos)s.className='current';frag.append(s)});const p=$('#prompt');p.innerHTML='';p.append(frag);updateNextKey()}
function currentText(){return missions[state.mission].rounds[state.round]}
function updateNextKey(){const ch=(currentText()[state.pos]||' ').toLowerCase();document.querySelectorAll('#keyboard .key').forEach(k=>k.classList.toggle('next',k.dataset.key===ch));let f='thumb';for(const k of rows.flat())if(k.c.toLowerCase()===ch)f=k.f;$('#nextHint').innerHTML=state.pos<currentText().length?`Next key: <b>${ch===' '?'SPACE':ch.toUpperCase()}</b> · ${fingerNames[f]}`:'Round complete'}
function focusInput(){$('#typeInput').focus({preventScroll:true})}
function handleKey(e){if($('#breakOverlay').hidden===false||$('#resultDialog').open||$('#keyboardDialog').open)return;if(e.ctrlKey||e.metaKey||e.altKey||e.key==='Tab'||e.key==='Escape')return;if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();toast('Keep moving forward — no corrections needed');return}if(e.key.length!==1)return;e.preventDefault();if(!state.start)startTimer();const expected=currentText()[state.pos].toLowerCase(),got=e.key.toLowerCase();state.typed++;const good=got===expected;if(good){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);state.score+=10+Math.min(state.streak,20)}else{state.errors.add(state.pos);state.streak=0;beep(false)};flashKey(got,good);state.pos++;if(good&&state.streak%10===0)beep(true);if(state.pos>=currentText().length)setTimeout(nextRound,120);else{renderPrompt();updateStats()}}
function startTimer(){state.start=Date.now();state.timer=setInterval(updateStats,500)}
function elapsed(){return state.start?(Date.now()-state.start)/1000:0}
function updateStats(){const sec=elapsed();$('#timer').textContent=`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`;const wpm=sec?Math.round((state.correct/5)/(sec/60)):0;const acc=state.typed?Math.round(state.correct/state.typed*100):100;$('#wpm').textContent=wpm;$('#accuracy').textContent=acc+'%';$('#streak').textContent=state.streak;$('#score').textContent=state.score.toLocaleString()}
function nextRound(){if(state.round<missions[state.mission].rounds.length-1){state.round++;state.pos=0;state.errors=new Set();$('#roundLabel').textContent=`ROUND ${state.round+1} / ${missions[state.mission].rounds.length}`;renderPrompt();toast(`Round ${state.round+1} — keep the rhythm`)}else completeMission()}
function completeMission(){clearInterval(state.timer);const sec=Math.max(elapsed(),1),wpm=Math.round((state.correct/5)/(sec/60)),acc=Math.round(state.correct/state.typed*100),earned=Math.round(80+state.score/10+(acc>=95?150:0));state.xp+=earned;if(!state.completed.includes(state.mission))state.completed.push(state.mission);state.unlocked=Math.max(state.unlocked,Math.min(state.mission+1,missions.length-1));save();const best=Math.max(Number(localStorage.getItem('rhq-best')||0),wpm);localStorage.setItem('rhq-best',best);$('#bestWpm').textContent=best;$('#resultTitle').textContent=acc>=95?'Clean run!':'Mission cleared!';$('#resultMessage').textContent=acc>=95?'Accuracy bonus earned. Your rhythm is taking shape.':'Nice progress. Replay this mission to push accuracy above 95%.';$('#resultWpm').textContent=wpm;$('#resultAccuracy').textContent=acc+'%';$('#resultXp').textContent='+'+earned;$('#nextMissionBtn').textContent=state.mission===missions.length-1?'Play summit again':'Continue to mission '+(state.mission+2);$('#resultDialog').showModal();renderMissions();updateRank();beep(true)}
function updateRank(){const level=Math.floor(state.xp/300)+1,within=state.xp%300,names=['Home Scout','Rhythm Finder','Key Ranger','Flow Keeper','Summit Typist'];$('#levelNumber').textContent=level;$('#rankName').textContent=names[Math.min(level-1,names.length-1)];$('#xpBar').style.width=(within/3)+'%';$('#xpLabel').textContent=`${within} / 300 XP`;$('#soundBtn').setAttribute('aria-pressed',state.sound);$('#soundBtn').textContent=state.sound?'♪':'×'}
function flashKey(ch,good){const key=document.querySelector(`#keyboard .key[data-key="${CSS.escape(ch)}"]`);if(key){key.classList.add('hit');if(!good)key.style.background='var(--orange)';setTimeout(()=>{key.classList.remove('hit');key.style.background=''},120)}}
function beep(win){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=win?660:180;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.09);o.start();o.stop(c.currentTime+.1)}catch(e){}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),1800)}
function startBreak(){clearInterval(state.timer);state.pauseAt=Date.now();$('#breakOverlay').hidden=false;let left=30;$('#breakTimer').textContent='0:30';state.breakInterval=setInterval(()=>{left--;$('#breakTimer').textContent='0:'+String(left).padStart(2,'0');if(left<=0)endBreak()},1000)}
function endBreak(){clearInterval(state.breakInterval);$('#breakOverlay').hidden=true;if(state.start){state.start+=Date.now()-state.pauseAt;state.timer=setInterval(updateStats,500)}focusInput()}

const keyTrail=[];
function keyLabel(key){const names={' ':'SPACE',Enter:'ENTER',Backspace:'BACKSPACE',Delete:'DELETE',Escape:'ESC',ArrowUp:'↑',ArrowDown:'↓',ArrowLeft:'←',ArrowRight:'→',Control:'CTRL'};return names[key]||key.toUpperCase()}
function monitorKey(e,down=true){
  const label=keyLabel(e.key);
  if(down&&!e.repeat){keyTrail.push(label);if(keyTrail.length>7)keyTrail.shift();$('#pressedKey').textContent=label;$('#keyHistory').textContent=keyTrail.join('  ·  ')}
  document.querySelectorAll('#monitorKeyboard .key').forEach(k=>{if(k.dataset.key===(e.key.length===1?e.key.toLowerCase():e.key))k.classList.toggle('monitor-pressed',down)});
}
function restoreMonitor(){
  try{const p=JSON.parse(localStorage.getItem('rhq-monitor'));if(!p)return;const m=$('#keyMonitor');if(p.min)m.classList.add('minimized');if(p.hidden)m.classList.add('hidden');if(Number.isFinite(p.left)&&Number.isFinite(p.top)){m.style.left=p.left+'px';m.style.top=p.top+'px';m.style.right='auto';m.style.bottom='auto'}$('#minimizeMonitor').textContent=p.min?'+':'−';$('#minimizeMonitor').setAttribute('aria-expanded',!p.min);$('#keyMonitorBtn').setAttribute('aria-pressed',!p.hidden)}catch(e){}
}
function saveMonitor(){const m=$('#keyMonitor'),r=m.getBoundingClientRect();let old={};try{old=JSON.parse(localStorage.getItem('rhq-monitor'))||{}}catch(e){}localStorage.setItem('rhq-monitor',JSON.stringify({left:r.width?r.left:old.left,top:r.height?r.top:old.top,min:m.classList.contains('minimized'),hidden:m.classList.contains('hidden')}))}
function makeMonitorDraggable(){
  const handle=$('#monitorHandle'),monitor=$('#keyMonitor');let drag=null;
  handle.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=monitor.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};handle.setPointerCapture(e.pointerId)});
  handle.addEventListener('pointermove',e=>{if(!drag)return;const left=Math.max(0,Math.min(innerWidth-monitor.offsetWidth,e.clientX-drag.x)),top=Math.max(0,Math.min(innerHeight-monitor.offsetHeight,e.clientY-drag.y));monitor.style.left=left+'px';monitor.style.top=top+'px';monitor.style.right='auto';monitor.style.bottom='auto'});
  handle.addEventListener('pointerup',()=>{if(drag){drag=null;saveMonitor()}});
}

load();buildKeyboard($('#keyboard'));buildKeyboard($('#dialogKeyboard'));buildKeyboard($('#monitorKeyboard'));restoreMonitor();makeMonitorDraggable();renderMissions();renderMission();$('#bestWpm').textContent=localStorage.getItem('rhq-best')||'—';
document.addEventListener('keydown',e=>monitorKey(e,true),true);document.addEventListener('keyup',e=>monitorKey(e,false),true);
$('#typeInput').addEventListener('keydown',handleKey);document.addEventListener('click',e=>{if(!e.target.closest('button,dialog,.key-monitor'))focusInput()});$('#focusBtn').onclick=focusInput;$('#guideBtn').onclick=()=>$('#keyboardDialog').showModal();$('.dialog-close').onclick=()=>$('#keyboardDialog').close();$('#keyMonitorBtn').onclick=()=>{const m=$('#keyMonitor'),show=m.classList.contains('hidden');m.classList.toggle('hidden',!show);$('#keyMonitorBtn').setAttribute('aria-pressed',show);saveMonitor();if(show)focusInput()};$('#minimizeMonitor').onclick=()=>{const m=$('#keyMonitor'),min=!m.classList.contains('minimized');m.classList.toggle('minimized',min);$('#minimizeMonitor').textContent=min?'+':'−';$('#minimizeMonitor').setAttribute('aria-expanded',!min);saveMonitor();setTimeout(focusInput)};$('#soundBtn').onclick=()=>{state.sound=!state.sound;save();updateRank()};$('#resetBtn').onclick=()=>{if(confirm('Reset all mission progress and personal bests?')){localStorage.removeItem('rhq-progress');localStorage.removeItem('rhq-best');localStorage.removeItem('rhq-monitor');location.reload()}};$('#nextMissionBtn').onclick=()=>{const next=state.mission<missions.length-1?state.mission+1:state.mission;$('#resultDialog').close();selectMission(next)};$('#breakBtn').onclick=startBreak;$('#skipBreak').onclick=endBreak;window.addEventListener('resize',()=>{const m=$('#keyMonitor'),r=m.getBoundingClientRect();if(r.right>innerWidth)m.style.left=Math.max(0,innerWidth-r.width-10)+'px';if(r.bottom>innerHeight)m.style.top=Math.max(0,innerHeight-r.height-10)+'px'});window.addEventListener('load',()=>setTimeout(focusInput,200));
